package com.myspace.decisiontabletest;

/**
 * This class was automatically generated by the data modeler tool.
 */

@javax.persistence.Entity
public class BusinessObject implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.lang.String name;

	private java.lang.String mainNum;

	private java.lang.String formNum;

	private java.lang.Boolean red_Eye;

	private java.lang.Boolean eye_Pain;

	private java.lang.Boolean eye_Itch;

	private java.lang.Boolean circumciliary_Injection;

	private java.lang.Boolean headache;

	private java.lang.Boolean eyelid_Swelling;

	private java.lang.Boolean tearing;

	private java.lang.Boolean blurred_Vision;

	private java.lang.Boolean metamorphopsia;

	private java.lang.Boolean floaters;

	private java.lang.Boolean photopsia;

	private java.lang.Boolean unilateral;

	private java.lang.Boolean RAPD;

	private java.lang.String finalNum;

	private java.lang.String gender;

	@javax.persistence.GeneratedValue(generator = "BUSINESSOBJECT_ID_GENERATOR", strategy = javax.persistence.GenerationType.AUTO)
	@javax.persistence.Id
	@javax.persistence.SequenceGenerator(sequenceName = "BUSINESSOBJECT_ID_SEQ", name = "BUSINESSOBJECT_ID_GENERATOR")
	private java.lang.Long id;

	private java.lang.String diagnosis;

	private java.lang.String disposition;

	private java.lang.String plan;

	public BusinessObject() {
	}

	public java.lang.String getName() {
		return this.name;
	}

	public void setName(java.lang.String name) {
		this.name = name;
	}

	public java.lang.String getMainNum() {
		return this.mainNum;
	}

	public void setMainNum(java.lang.String mainNum) {
		this.mainNum = mainNum;
	}

	public java.lang.String getFormNum() {
		return this.formNum;
	}

	public void setFormNum(java.lang.String formNum) {
		this.formNum = formNum;
	}

	public java.lang.Boolean getRed_Eye() {
		return this.red_Eye;
	}

	public void setRed_Eye(java.lang.Boolean red_Eye) {
		this.red_Eye = red_Eye;
	}

	public java.lang.Boolean getEye_Pain() {
		return this.eye_Pain;
	}

	public void setEye_Pain(java.lang.Boolean eye_Pain) {
		this.eye_Pain = eye_Pain;
	}

	public java.lang.Boolean getEye_Itch() {
		return this.eye_Itch;
	}

	public void setEye_Itch(java.lang.Boolean eye_Itch) {
		this.eye_Itch = eye_Itch;
	}

	public java.lang.Boolean getCircumciliary_Injection() {
		return this.circumciliary_Injection;
	}

	public void setCircumciliary_Injection(
			java.lang.Boolean circumciliary_Injection) {
		this.circumciliary_Injection = circumciliary_Injection;
	}

	public java.lang.Boolean getHeadache() {
		return this.headache;
	}

	public void setHeadache(java.lang.Boolean headache) {
		this.headache = headache;
	}

	public java.lang.Boolean getEyelid_Swelling() {
		return this.eyelid_Swelling;
	}

	public void setEyelid_Swelling(java.lang.Boolean eyelid_Swelling) {
		this.eyelid_Swelling = eyelid_Swelling;
	}

	public java.lang.Boolean getTearing() {
		return this.tearing;
	}

	public void setTearing(java.lang.Boolean tearing) {
		this.tearing = tearing;
	}

	public java.lang.Boolean getBlurred_Vision() {
		return this.blurred_Vision;
	}

	public void setBlurred_Vision(java.lang.Boolean blurred_Vision) {
		this.blurred_Vision = blurred_Vision;
	}

	public java.lang.Boolean getMetamorphopsia() {
		return this.metamorphopsia;
	}

	public void setMetamorphopsia(java.lang.Boolean metamorphopsia) {
		this.metamorphopsia = metamorphopsia;
	}

	public java.lang.Boolean getFloaters() {
		return this.floaters;
	}

	public void setFloaters(java.lang.Boolean floaters) {
		this.floaters = floaters;
	}

	public java.lang.Boolean getPhotopsia() {
		return this.photopsia;
	}

	public void setPhotopsia(java.lang.Boolean photopsia) {
		this.photopsia = photopsia;
	}

	public java.lang.Boolean getUnilateral() {
		return this.unilateral;
	}

	public void setUnilateral(java.lang.Boolean unilateral) {
		this.unilateral = unilateral;
	}

	public java.lang.Boolean getRAPD() {
		return this.RAPD;
	}

	public void setRAPD(java.lang.Boolean RAPD) {
		this.RAPD = RAPD;
	}

	public java.lang.String getFinalNum() {
		return this.finalNum;
	}

	public void setFinalNum(java.lang.String finalNum) {
		this.finalNum = finalNum;
	}

	public java.lang.String getGender() {
		return this.gender;
	}

	public void setGender(java.lang.String gender) {
		this.gender = gender;
	}

	public java.lang.Long getId() {
		return this.id;
	}

	public void setId(java.lang.Long id) {
		this.id = id;
	}

	public java.lang.String getDiagnosis() {
		return this.diagnosis;
	}

	public void setDiagnosis(java.lang.String diagnosis) {
		this.diagnosis = diagnosis;
	}

	public java.lang.String getDisposition() {
		return this.disposition;
	}

	public void setDisposition(java.lang.String disposition) {
		this.disposition = disposition;
	}

	public java.lang.String getPlan() {
		return this.plan;
	}

	public void setPlan(java.lang.String plan) {
		this.plan = plan;
	}

	public BusinessObject(java.lang.String name, java.lang.String mainNum,
			java.lang.String formNum, java.lang.Boolean red_Eye,
			java.lang.Boolean eye_Pain, java.lang.Boolean eye_Itch,
			java.lang.Boolean circumciliary_Injection,
			java.lang.Boolean headache, java.lang.Boolean eyelid_Swelling,
			java.lang.Boolean tearing, java.lang.Boolean blurred_Vision,
			java.lang.Boolean metamorphopsia, java.lang.Boolean floaters,
			java.lang.Boolean photopsia, java.lang.Boolean unilateral,
			java.lang.Boolean RAPD, java.lang.String finalNum,
			java.lang.String gender, java.lang.Long id,
			java.lang.String diagnosis, java.lang.String disposition,
			java.lang.String plan) {
		this.name = name;
		this.mainNum = mainNum;
		this.formNum = formNum;
		this.red_Eye = red_Eye;
		this.eye_Pain = eye_Pain;
		this.eye_Itch = eye_Itch;
		this.circumciliary_Injection = circumciliary_Injection;
		this.headache = headache;
		this.eyelid_Swelling = eyelid_Swelling;
		this.tearing = tearing;
		this.blurred_Vision = blurred_Vision;
		this.metamorphopsia = metamorphopsia;
		this.floaters = floaters;
		this.photopsia = photopsia;
		this.unilateral = unilateral;
		this.RAPD = RAPD;
		this.finalNum = finalNum;
		this.gender = gender;
		this.id = id;
		this.diagnosis = diagnosis;
		this.disposition = disposition;
		this.plan = plan;
	}

}