package com.myspace.decisiontabletest;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Form6Object implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.lang.Boolean diabetes;
	private java.lang.Boolean reduced_Red_Reflex;

	private java.lang.Boolean improve_Pinhole;

	private java.lang.Boolean tear_Down_Cheek;

	public Form6Object() {
	}

	public java.lang.Boolean getDiabetes() {
		return this.diabetes;
	}

	public void setDiabetes(java.lang.Boolean diabetes) {
		this.diabetes = diabetes;
	}

	public java.lang.Boolean getReduced_Red_Reflex() {
		return this.reduced_Red_Reflex;
	}

	public void setReduced_Red_Reflex(java.lang.Boolean reduced_Red_Reflex) {
		this.reduced_Red_Reflex = reduced_Red_Reflex;
	}

	public java.lang.Boolean getImprove_Pinhole() {
		return this.improve_Pinhole;
	}

	public void setImprove_Pinhole(java.lang.Boolean improve_Pinhole) {
		this.improve_Pinhole = improve_Pinhole;
	}

	public java.lang.Boolean getTear_Down_Cheek() {
		return this.tear_Down_Cheek;
	}

	public void setTear_Down_Cheek(java.lang.Boolean tear_Down_Cheek) {
		this.tear_Down_Cheek = tear_Down_Cheek;
	}

	public Form6Object(java.lang.Boolean diabetes,
			java.lang.Boolean reduced_Red_Reflex,
			java.lang.Boolean improve_Pinhole, java.lang.Boolean tear_Down_Cheek) {
		this.diabetes = diabetes;
		this.reduced_Red_Reflex = reduced_Red_Reflex;
		this.improve_Pinhole = improve_Pinhole;
		this.tear_Down_Cheek = tear_Down_Cheek;
	}

}