package com.myspace.decisiontabletest;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Form1Object implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.lang.Boolean improve_Lubricants;
	private java.lang.Boolean diabetes;
	private java.lang.Boolean contact_Lens;
	private java.lang.Boolean trauma;
	private java.lang.Boolean white_Spot_Cornea;
	private java.lang.Boolean mid_Dilated_Pupils;
	private java.lang.Boolean reduced_Red_Reflex;

	private java.lang.Boolean improve_Pinhole;

	private java.lang.Boolean resolve_Lubricants;

	private java.lang.Boolean tear_Down_Cheek;

	public Form1Object() {
	}

	public java.lang.Boolean getImprove_Lubricants() {
		return this.improve_Lubricants;
	}

	public void setImprove_Lubricants(java.lang.Boolean improve_Lubricants) {
		this.improve_Lubricants = improve_Lubricants;
	}

	public java.lang.Boolean getDiabetes() {
		return this.diabetes;
	}

	public void setDiabetes(java.lang.Boolean diabetes) {
		this.diabetes = diabetes;
	}

	public java.lang.Boolean getContact_Lens() {
		return this.contact_Lens;
	}

	public void setContact_Lens(java.lang.Boolean contact_Lens) {
		this.contact_Lens = contact_Lens;
	}

	public java.lang.Boolean getTrauma() {
		return this.trauma;
	}

	public void setTrauma(java.lang.Boolean trauma) {
		this.trauma = trauma;
	}

	public java.lang.Boolean getWhite_Spot_Cornea() {
		return this.white_Spot_Cornea;
	}

	public void setWhite_Spot_Cornea(java.lang.Boolean white_Spot_Cornea) {
		this.white_Spot_Cornea = white_Spot_Cornea;
	}

	public java.lang.Boolean getMid_Dilated_Pupils() {
		return this.mid_Dilated_Pupils;
	}

	public void setMid_Dilated_Pupils(java.lang.Boolean mid_Dilated_Pupils) {
		this.mid_Dilated_Pupils = mid_Dilated_Pupils;
	}

	public java.lang.Boolean getReduced_Red_Reflex() {
		return this.reduced_Red_Reflex;
	}

	public void setReduced_Red_Reflex(java.lang.Boolean reduced_Red_Reflex) {
		this.reduced_Red_Reflex = reduced_Red_Reflex;
	}

	public java.lang.Boolean getImprove_Pinhole() {
		return this.improve_Pinhole;
	}

	public void setImprove_Pinhole(java.lang.Boolean improve_Pinhole) {
		this.improve_Pinhole = improve_Pinhole;
	}

	public java.lang.Boolean getResolve_Lubricants() {
		return this.resolve_Lubricants;
	}

	public void setResolve_Lubricants(java.lang.Boolean resolve_Lubricants) {
		this.resolve_Lubricants = resolve_Lubricants;
	}

	public java.lang.Boolean getTear_Down_Cheek() {
		return this.tear_Down_Cheek;
	}

	public void setTear_Down_Cheek(java.lang.Boolean tear_Down_Cheek) {
		this.tear_Down_Cheek = tear_Down_Cheek;
	}

	public Form1Object(java.lang.Boolean improve_Lubricants,
			java.lang.Boolean diabetes, java.lang.Boolean contact_Lens,
			java.lang.Boolean trauma, java.lang.Boolean white_Spot_Cornea,
			java.lang.Boolean mid_Dilated_Pupils,
			java.lang.Boolean reduced_Red_Reflex,
			java.lang.Boolean improve_Pinhole,
			java.lang.Boolean resolve_Lubricants,
			java.lang.Boolean tear_Down_Cheek) {
		this.improve_Lubricants = improve_Lubricants;
		this.diabetes = diabetes;
		this.contact_Lens = contact_Lens;
		this.trauma = trauma;
		this.white_Spot_Cornea = white_Spot_Cornea;
		this.mid_Dilated_Pupils = mid_Dilated_Pupils;
		this.reduced_Red_Reflex = reduced_Red_Reflex;
		this.improve_Pinhole = improve_Pinhole;
		this.resolve_Lubricants = resolve_Lubricants;
		this.tear_Down_Cheek = tear_Down_Cheek;
	}

}